Repository mattermost/mattermost-plugin-profanity-filter, pull requests merged in 2020-10, with the labels that each got.

#24 Use regex to match badwords
  README.md
  plugin.json
  server/configuration.go
  server/configuration_test.go
  server/plugin.go
  server/plugin_test.go
Labels: 4: Reviews Complete

#27 Change permission for manifest to 0600
  build/manifest/main.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#23 Add warning message when post is rejected
  README.md
  images/post-censored.gif
  images/post-rejected.gif
  plugin.json
  server/configuration.go
  server/plugin.go
Labels: 4: Reviews Complete, QA Review Done

#29 Clearer gif for rejected post
  images/post-rejected.gif
Labels: Hacktoberfest, hacktoberfest-accepted

#17 Release v1.0.0
  plugin.json
  server/manifest.go
Labels: 3: QA Review

#30 [GH-25] Adds option to disable filtering for bot messages
  plugin.json
  server/configuration.go
  server/plugin.go
  server/plugin_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted
